# In This Notebook, We're to going to descover tensors with TensorFlow

* Introduction to Tensors
* Getting Informations from Tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.functions (A Way to speed up your regular python functions)
* Using GPUs With TensorFlow (or TPUs)
* Exercises


## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [2]:
# Create Tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions
scaler.ndim

0

In [4]:
vector = tf.constant([10,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10.,7.],
                      [10.,10.]],
                     dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [10., 10.]], dtype=float16)>

In [7]:
print(matrix.ndim)
print(matrix.shape)

2
(2, 2)


In [8]:
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,22,33]]],dtype=tf.int32)
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 22, 33]]], dtype=int32)>

In [9]:
tensor.ndim

3

### Creating tensor with tf.variable()

In [10]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
# Change one of the elements
# changeable_tensor[0] = 0 Cant be done
changeable_tensor[0].assign(7)
changeable_tensor
# unchangeable_tensor[0].assign(7) Cant be done

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensor

In [12]:
random = tf.random.Generator.from_seed(42)
print(random)

random_1 = random.normal(shape=(3,2))
print('\n',50*'*','\n')
print(random_1)

random_2 = random.normal(shape=(3,2))
print('\n',50*'*','\n')
print(random_2)



 ************************************************** 

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)

 ************************************************** 

tf.Tensor(
[[ 0.17522676  0.71105534]
 [ 0.5488243   0.14896014]
 [-0.54757965  0.61634356]], shape=(3, 2), dtype=float32)


### Shuffle The order of elements in a tensor

In [13]:
not_shoffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

In [14]:
print(not_shoffled)
print('\n',50*'*','\n')
tf.random.shuffle(not_shoffled)

# Rerun and will shuffle it again

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)

 ************************************************** 



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [15]:
print(not_shoffled)
print('\n',50*'*','\n')
tf.random.shuffle(not_shoffled,seed=42)

# Rerun and will shuffle it again

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)

 ************************************************** 



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [16]:
print(not_shoffled)
print('\n',50*'*','\n')
tf.random.set_seed(42)
tf.random.shuffle(not_shoffled,seed=42)

# Won't shuffle it again with rerun

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)

 ************************************************** 



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
print(not_shoffled)
print('\n',50*'*','\n')
tf.random.set_seed(42) # Global random seed
tf.random.shuffle(not_shoffled,seed=78) # operational level random seed

# Won't shuffle it again with rerun


# seed included in shuffle method is resetting the global seed but
# can't create the seed variable

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)

 ************************************************** 



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

### Otherwise to make tensors

In [18]:
print(tf.ones((3,4))) # ()
print(tf.zeros([3,4])) # []


tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


### Turn Numpy arrays into tensors
The main difference between Numpy array and TensorFlow Tensors is that tensors can be run on a GPU way faster than arrays

In [19]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A,shape=(3,2,4))
A,50*'*',B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 '**************************************************',
 <tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

## Getting Informations from Tensors
* Shape
* Rank
* Axis or Dimensions
* Size

In [21]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor),tf.size(rank_4_tensor).numpy()

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 120)

### Indexing tensors
Tensors can be indexed jsut like python lists

In [24]:
rank_4_tensor[0][0] # = rank_4_tensor[0,0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [25]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [26]:
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [27]:
# Add in extra dimensions to rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # =rank_2_tensor[:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [28]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [29]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating Tensors (Tensors Operations)

In [30]:
tensor + 10

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[11, 12, 13],
        [14, 15, 16]],

       [[17, 18, 19],
        [20, 32, 43]]], dtype=int32)>

In [31]:
tensor * 10

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 220, 330]]], dtype=int32)>

In [32]:
tf.multiply(tensor,10) # Higher speed

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 220, 330]]], dtype=int32)>

### Matrix Multiplication
In Machine Learning, Matrix Multiplication is one of the most common tensor operations.
> matrix_1(m*n) == matrix_2(n*p)
>> #rows of mat1 == #cols of mat2

> output matrix has (m,p)

In [33]:
tensor = tf.constant([[1,2],
                     [5,10]])

In [34]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 11,  22],
       [ 55, 110]], dtype=int32)>

In [35]:
tensor * tensor # Normal item by item Multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  1,   4],
       [ 25, 100]], dtype=int32)>

In [36]:
tensor @ tensor # Matrix Multiplication (Dot Product)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 11,  22],
       [ 55, 110]], dtype=int32)>

In [37]:
X = tf.constant([[1,2,3],
                 [4,5,6]])
Y = tf.constant([[2,5,10],
                 [1,3,5]])

In [38]:
tf.tensordot(tf.transpose(X),Y,axes=1),tf.matmul(tf.transpose(X),Y)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 6, 17, 30],
        [ 9, 25, 45],
        [12, 33, 60]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 6, 17, 30],
        [ 9, 25, 45],
        [12, 33, 60]], dtype=int32)>)

In [39]:
tf.tensordot(tf.reshape(X,shape=(3,2)),Y,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4, 11, 20],
       [10, 27, 50],
       [16, 43, 80]], dtype=int32)>

### Changing The DataType of a Tensor

In [40]:
B = tf.constant([1.3,5.9])
B.dtype

tf.float32

In [41]:
C = tf.constant([3,5])
C.dtype

tf.int32

In [42]:
# Change From Float32 to Float16 (Reduce Precision)
D = tf.cast(B,dtype=tf.float16)
D.dtype

tf.float16

In [43]:
# Change From Int32 to Float32
tf.cast(C,dtype=tf.float32)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>

### Tensor Aggregation

In [44]:
E = tf.constant(np.random.randint(0,100,size=50))
tf.reshape(E,shape=(10,5))

<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
array([[68, 57, 60, 20, 17],
       [ 6, 63, 66, 94, 85],
       [ 9, 10, 76, 46,  5],
       [60, 15, 11, 13, 89],
       [17, 32,  0, 90, 68],
       [28, 76, 64,  4, 40],
       [65, 57,  9, 12, 85],
       [53, 77, 22, 78, 49],
       [41, 28, 70, 71, 32],
       [53, 53, 69, 68, 16]])>

In [45]:
# Find Minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [46]:
# Find Maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=94>

In [47]:
# Find Mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [48]:
# Find Sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2297>

In [49]:
# Find Variance
import tensorflow_probability as tfp
tfp.stats.variance(E), tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int64, numpy=777>,
 <tf.Tensor: shape=(), dtype=float32, numpy=776.4564>)

In [50]:
# Find Standard Deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)) # Data Type has to be Float

<tf.Tensor: shape=(), dtype=float32, numpy=27.864967>

#### Finding The Positional Maximum and Minimus

In [51]:
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [52]:
# Find The positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [53]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [54]:
# Find The minimum using the positional mimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (remove all single dimensions)

In [55]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [56]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [57]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot Encoding Tensors

In [58]:
ls = [0,1,2,3] # could be[red,green,blue,purple]
tf.one_hot(ls,depth=4) # 4 = len(ls)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [59]:
# Specify custom values for one hot encoding
tf.one_hot(ls,depth=4,on_value='Aaref',off_value='NUNU')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Aaref', b'NUNU', b'NUNU', b'NUNU'],
       [b'NUNU', b'Aaref', b'NUNU', b'NUNU'],
       [b'NUNU', b'NUNU', b'Aaref', b'NUNU'],
       [b'NUNU', b'NUNU', b'NUNU', b'Aaref']], dtype=object)>

## Tensors And Numpy
TensorFlow Interacts beautifully with Numpy arrays.

In [60]:
# Create a Tensor directly from numpy array
J = tf.constant(np.array([3.,4.,7.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 7.])>

In [61]:
type(J), np.array(J), type(np.array(J))

(tensorflow.python.framework.ops.EagerTensor,
 array([3., 4., 7.]),
 numpy.ndarray)

In [62]:
J.numpy(), type(J.numpy())

(array([3., 4., 7.]), numpy.ndarray)

In [63]:
numpy_J = tf.constant(np.array([3.,7.]))
tensor_J = tf.constant([3.,7.])
print('Tensor from Numpy array: ', numpy_J.dtype)
print('Tensor from default tensorflow: ', tensor_J.dtype)

Tensor from Numpy array:  <dtype: 'float64'>
Tensor from default tensorflow:  <dtype: 'float32'>



## GPUs TPUs

In [65]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [66]:
!nvidia-smi

Thu Oct 19 08:07:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0    35W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

⛏***NOTE:*** If You have access to a Cuda-enabled GPU, TensorFlow will automaticly use it whenever possible

